apiVersion: v1
kind: Service
metadata:
  name: identity
  labels:
    app.kubernetes.io/name: identity
    app.kubernetes.io/part-of: sharkpay
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: identity
  ports:
  - name: http
    port: 8081
    targetPort: http
    protocol: TCP
