apiVersion: v1
kind: Service
metadata:
  name: wallet
  labels:
    app.kubernetes.io/name: wallet
    app.kubernetes.io/part-of: sharkpay
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wallet
  ports:
  - name: http
    port: 8082
    targetPort: http
    protocol: TCP
