apiVersion: v1
kind: Service
metadata:
  name: ledger
  labels:
    app.kubernetes.io/name: ledger
    app.kubernetes.io/part-of: sharkpay
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ledger
  ports:
  - name: http
    port: 8090
    targetPort: http
    protocol: TCP
