package com.sharkpay.gateway.domain;

import java.time.Duration;
import java.time.Instant;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;

/**
 * An API key credential (domain object). The stored secret is a SHA-256
 * hash — 64 lowercase hex chars — never the plaintext; the plaintext
 * {@code sp_live_...} value is generated by the {@code Randomness} port,
 * shown exactly once in the creation response and then discarded.
 *
 * <p>Rotation keeps the superseded key valid inside a grace window
 * ({@value #GRACE_WINDOW} hours, docs/SECURITY.md §2) so clients can swap
 * secrets without downtime; after the window the old secret is rejected
 * exactly like an unknown key (401).</p>
 *
 * @param id              key id ({@code key_...})
 * @param principalId     owning principal (the caller every resource is scoped to)
 * @param secretHash      SHA-256 hex of the plaintext secret (64 hex chars)
 * @param scopes          fail-closed scope catalog subset
 * @param status          lifecycle status
 * @param graceExpiresAt  only for {@code ROTATING}: the instant the old secret stops working
 * @param rpmLimit        requests-per-minute quota
 * @param monthlyLimit    requests-per-month quota
 * @param createdAt       audit
 * @param updatedAt       audit
 */
public record ApiKey(String id, UUID principalId, String secretHash, Set<Scope> scopes,
                     ApiKeyStatus status, Instant graceExpiresAt, int rpmLimit,
                     long monthlyLimit, Instant createdAt, Instant updatedAt) {

    /** SHA-256 hex digest length (the api_keys.secret_hash column width). */
    public static final int SECRET_HASH_HEX_LENGTH = 64;

    /** Rotation grace window (docs/SECURITY.md §2: 24 h overlap). */
    public static final Duration GRACE_WINDOW = Duration.ofHours(24);

    /** Minimum plaintext secret length ({@code sp_live_} + 43 base62 chars). */
    public static final int MIN_SECRET_LENGTH = 16;

    public ApiKey {
        Objects.requireNonNull(id, "id is required");
        Objects.requireNonNull(principalId, "principalId is required");
        Objects.requireNonNull(secretHash, "secretHash is required");
        Objects.requireNonNull(scopes, "scopes are required");
        Objects.requireNonNull(status, "status is required");
        Objects.requireNonNull(createdAt, "createdAt is required");
        Objects.requireNonNull(updatedAt, "updatedAt is required");
        if (secretHash.length() != SECRET_HASH_HEX_LENGTH
                || !secretHash.chars().allMatch(c -> (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f'))) {
            throw new IllegalArgumentException(
                    "secretHash must be " + SECRET_HASH_HEX_LENGTH + " lowercase hex chars");
        }
        if (scopes.isEmpty()) {
            throw new IllegalArgumentException("an api key must carry at least one scope");
        }
        if (rpmLimit <= 0 || monthlyLimit <= 0) {
            throw new IllegalArgumentException("quota limits must be positive");
        }
        if (status == ApiKeyStatus.ROTATING && graceExpiresAt == null) {
            throw new IllegalArgumentException("a rotating key requires a grace expiry");
        }
        if (status != ApiKeyStatus.ROTATING && graceExpiresAt != null) {
            throw new IllegalArgumentException("only rotating keys carry a grace expiry");
        }
    }

    /** A freshly created key with its first secret hash. */
    public static ApiKey active(String id, UUID principalId, String secretHash, Set<Scope> scopes,
                                int rpmLimit, long monthlyLimit, Instant now) {
        return new ApiKey(id, principalId, secretHash, Set.copyOf(scopes), ApiKeyStatus.ACTIVE,
                null, rpmLimit, monthlyLimit, now, now);
    }

    /**
     * Marks this key superseded by a rotation: still valid until the grace
     * window expires ({@link #GRACE_WINDOW} from {@code now}), 401 after.
     */
    public ApiKey markRotating(Instant now) {
        return new ApiKey(id, principalId, secretHash, scopes, ApiKeyStatus.ROTATING,
                now.plus(GRACE_WINDOW), rpmLimit, monthlyLimit, createdAt, now);
    }

    /** Kills the key immediately (revoked secrets always 401). */
    public ApiKey revoked(Instant now) {
        return new ApiKey(id, principalId, secretHash, scopes, ApiKeyStatus.REVOKED,
                null, rpmLimit, monthlyLimit, createdAt, now);
    }

    /**
     * Whether this key authenticates at the given instant: active keys
     * always; rotating keys only inside their grace window; revoked keys
     * never.
     */
    public boolean authenticatesAt(Instant now) {
        return switch (status) {
            case ACTIVE -> true;
            case ROTATING -> now.isBefore(graceExpiresAt);
            case REVOKED -> false;
        };
    }

    /** Fail-closed scope test — unknown scopes simply are not held. */
    public boolean hasScope(Scope required) {
        return scopes.contains(required);
    }

    /** The grace expiry, empty unless rotating (for response bodies). */
    public Optional<Instant> graceExpiresAtOptional() {
        return status == ApiKeyStatus.ROTATING ? Optional.of(graceExpiresAt) : Optional.empty();
    }
}
