apiVersion: v1
kind: Service
metadata:
  name: payouts
  labels:
    app.kubernetes.io/name: payouts
    app.kubernetes.io/part-of: sharkpay
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payouts
  ports:
  - name: http
    port: 8086
    targetPort: http
    protocol: TCP
