apiVersion: v1
kind: Service
metadata:
  name: reconciliation
  labels:
    app.kubernetes.io/name: reconciliation
    app.kubernetes.io/part-of: sharkpay
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: reconciliation
  ports:
  - name: http
    port: 8087
    targetPort: http
    protocol: TCP
